tasks:
  - init: ./gradlew check
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - fwcd.kotlin@0.2.11:moh8IDanzsIlhtK2IeiLmQ==
    - vscode-icons-team.vscode-icons@9.2.0:Ijpf7hzDdyz46hvWWPc41Q==