/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package midnight.fortune.oven

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test fun fives() {
        MicroKanren.run { 
            fresh { x ->
                (x eq Term.TAtom("5")) disj (x eq Term.TAtom("10"))
            }
        }.invoke(State.ZERO).take(10).toList().also(::println)
    }
}
